import { MaintenanceRecord } from "../interface/maintenanceRecord";
import { Equipment } from "../interface/equipment";

export const maintenanceData: MaintenanceRecord[] = [
  {
    id: "MR001",
    equipmentId: "EQ1001",
    date: new Date("2025-03-10"),
    type: "Preventive",
    technician: "John Doe",
    hoursSpent: 2,
    description: "Routine inspection and lubrication of moving parts.",
    partsReplaced: ["Air Filter"],
    priority: "Low",
    completionStatus: "Complete",
  },
  {
    id: "MR002",
    equipmentId: "EQ1002",
    date: new Date("2025-03-15"),
    type: "Repair",
    technician: "Jane Smith",
    hoursSpent: 4,
    description: "Replaced faulty motor and recalibrated system.",
    partsReplaced: ["Motor", "Belt"],
    priority: "High",
    completionStatus: "Complete",
  },
  {
    id: "MR003",
    equipmentId: "EQ1003",
    date: new Date("2025-03-18"),
    type: "Emergency",
    technician: "Mike Johnson",
    hoursSpent: 6,
    description: "Emergency replacement of hydraulic valve due to leak.",
    partsReplaced: ["Hydraulic Valve"],
    priority: "High",
    completionStatus: "Incomplete",
  },
  {
    id: "MR004",
    equipmentId: "EQ1004",
    date: new Date("2025-03-20"),
    type: "Preventive",
    technician: "Alice Brown",
    hoursSpent: 1.5,
    description: "Checked coolant levels and cleaned radiator.",
    priority: "Medium",
    completionStatus: "Complete",
  },
  {
    id: "MR005",
    equipmentId: "EQ1005",
    date: new Date("2025-03-22"),
    type: "Repair",
    technician: "Chris Wilson",
    hoursSpent: 3,
    description: "Replaced damaged sensor and tested system.",
    partsReplaced: ["Temperature Sensor"],
    priority: "Medium",
    completionStatus: "Complete",
  },
  {
    id: "MR006",
    equipmentId: "EQ1006",
    date: new Date("2025-03-25"),
    type: "Emergency",
    technician: "David Lee",
    hoursSpent: 5,
    description: "Fixed malfunctioning control panel due to short circuit.",
    priority: "High",
    completionStatus: "Pending Parts",
  },
  {
    id: "MR007",
    equipmentId: "EQ1007",
    date: new Date("2025-03-28"),
    type: "Preventive",
    technician: "Laura Adams",
    hoursSpent: 1,
    description: "Lubricated conveyor belt and adjusted tension.",
    priority: "Low",
    completionStatus: "Complete",
  },
];

export const equipmentData: Equipment[] = [
  {
    id: "EQ1001",
    name: "Conveyor Belt 1",
    location: "Assembly Line 1",
    department: "Assembly",
    model: "CB-1001",
    serialNumber: "SN1001",
    installDate: new Date("2020-05-10"),
    status: "Retired",
  },
  {
    id: "EQ1002",
    name: "Drilling Machine 3",
    location: "Machining Area",
    department: "Machining",
    model: "DM-3000",
    serialNumber: "SN1002",
    installDate: new Date("2018-11-15"),
    status: "Operational",
  },
  {
    id: "EQ1003",
    name: "Hydraulic Press 5",
    location: "Production Area",
    department: "Assembly",
    model: "HP-5000",
    serialNumber: "SN1003",
    installDate: new Date("2019-07-30"),
    status: "Down",
  },
  {
    id: "EQ1004",
    name: "Cooling System 2",
    location: "Packaging Area",
    department: "Packaging",
    model: "CS-2000",
    serialNumber: "SN1004",
    installDate: new Date("2021-02-20"),
    status: "Operational",
  },
  {
    id: "EQ1005",
    name: "Injection Molding Machine 4",
    location: "Packaging Area",
    department: "Packaging",
    model: "IMM-4000",
    serialNumber: "SN1005",
    installDate: new Date("2017-08-12"),
    status: "Operational",
  },
  {
    id: "EQ1006",
    name: "Control Panel 8",
    location: "Shipping Area",
    department: "Shipping",
    model: "CP-8000",
    serialNumber: "SN1006",
    installDate: new Date("2022-01-01"),
    status: "Down",
  },
  {
    id: "EQ1007",
    name: "Conveyor Belt 3",
    location: "Assembly Line 2",
    department: "Assembly",
    model: "CB-3000",
    serialNumber: "SN1007",
    installDate: new Date("2020-09-15"),
    status: "Operational",
  },
];

export async function getMData(): Promise<MaintenanceRecord[]> {
  return maintenanceData;
}

export async function getEData(): Promise<Equipment[]> {
  return equipmentData;
}
